package bar;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class AdmLog extends javax.swing.JFrame {
    Connection c = null;
    ResultSet rst = null;
    Statement st = null;
    PreparedStatement pst;
    
    public AdmLog() {
        initComponents();
        c = Bar.getConnected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        right = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PF2 = new javax.swing.JPasswordField();
        B5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        B6 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        right.setBackground(new java.awt.Color(204, 0, 204));
        right.setPreferredSize(new java.awt.Dimension(400, 500));
        right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\1234.png")); // NOI18N
        right.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 149, -1, 149));

        jPanel1.add(right);
        right.setBounds(0, 0, 400, 500);

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setPreferredSize(new java.awt.Dimension(400, 500));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("ADMIN LOGIN");
        left.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 84, 248, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("USERNAME");
        left.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 144, 83, -1));

        TF2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TF2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF2ActionPerformed(evt);
            }
        });
        left.add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 170, 282, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("PASSWORD");
        left.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 216, 83, -1));

        PF2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        PF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF2ActionPerformed(evt);
            }
        });
        left.add(PF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 242, 282, 40));

        B5.setBackground(new java.awt.Color(204, 0, 204));
        B5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        B5.setForeground(new java.awt.Color(255, 255, 255));
        B5.setText("Login");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        left.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 324, -1, -1));

        jLabel4.setText("Don't have an account?");
        left.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 366, -1, -1));

        B6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        B6.setForeground(new java.awt.Color(204, 0, 204));
        B6.setText("Sign up");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        left.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 363, -1, -1));

        jCheckBox1.setBackground(new java.awt.Color(204, 0, 204));
        jCheckBox1.setText("SHOW PASSWORD");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        left.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 292, 153, -1));

        jButton1.setForeground(new java.awt.Color(204, 0, 204));
        jButton1.setText("<GO BACK ");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        left.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 20, -1, -1));

        jPanel1.add(left);
        left.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
     try{
        String user = TF2.getText();
        String pass = String.valueOf(PF2.getPassword());
              st = c.createStatement();
        String sql = "SELECT * FROM `admin` WHERE `username` = ? && `password` = ? ";
            pst = c.prepareStatement(sql);
             pst.setString(1, user);
              pst.setString(2, pass);
               rst = pst.executeQuery();
                if(rst.next()){
                   JOptionPane.showMessageDialog(rootPane, "Logged IN");
                       AdmMan adn = new AdmMan();
                       adn.setVisible(true);
                 }else{
                       JOptionPane.showMessageDialog(rootPane, "No Account Found", null, JOptionPane.ERROR_MESSAGE);
                 }
                 }catch(Exception e){
                  JOptionPane.showMessageDialog(rootPane, e, null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        regist signup = new regist();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_B6ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(jCheckBox1.isSelected()){
            PF2.setEchoChar((char)0);
        }else{
            PF2.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         LogIn In = new LogIn();
         In.setVisible(true);  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PF2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JPasswordField PF2;
    private javax.swing.JTextField TF2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel left;
    private javax.swing.JPanel right;
    // End of variables declaration//GEN-END:variables
}
