package bar;

public class LoadScr extends javax.swing.JFrame {

    /**
     * Creates new form LoadScr
     */
    public LoadScr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        background = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lbar = new javax.swing.JProgressBar();
        Lvalue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(204, 0, 204));
        background.setPreferredSize(new java.awt.Dimension(800, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("LOADING...");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 310, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("WELCOME");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 560, 100));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("SPORT'S BAR");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 340, 60));

        Lbar.setBackground(new java.awt.Color(204, 204, 204));
        Lbar.setForeground(new java.awt.Color(204, 0, 204));
        background.add(Lbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 800, 10));

        Lvalue.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        Lvalue.setForeground(new java.awt.Color(255, 255, 255));
        Lvalue.setText("0%");
        background.add(Lvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\home_background.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {   
        LoadScr scr = new LoadScr();
        scr.setVisible(true);
        LogIn log =new LogIn();
         
        
        try{
            for(int i=0;i<=100;i++){
                Thread.sleep(100);
                scr.Lvalue.setText(i +"%");
                
                if(i==10){
                    scr.jLabel4.setText("Turning On Modules");
                }
                if(i==20){
                    scr.jLabel4.setText("Loading Modules");
                }
                if(i==60){
                    scr.jLabel4.setText("Connecting To Database");
                }
                if(i==70){
                    scr.jLabel4.setText("Connection Successful!!");
                }
                if(i==78){
                    scr.jLabel4.setText("Launching System>>>>");
                }
                scr.Lbar.setValue(i);
                
            }
            log.setVisible(true);
        }catch(Exception e){
           
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Lbar;
    private javax.swing.JLabel Lvalue;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
