package bar;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class regist extends javax.swing.JFrame {

    Statement state;
    PreparedStatement pstate;
    ResultSet rs;
    public regist() {
        initComponents();
        Play();
    }
    private void Play(){
        try{
            Connection c = Bar.getConnected();
            Statement s = c.createStatement();
            String sql = "SELECT `username`, `password` FROM `registration` WHERE 1";
            ResultSet r = s.executeQuery(sql);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane,e);
        }
    }   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        right = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PF3 = new javax.swing.JPasswordField();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PF4 = new javax.swing.JPasswordField();
        CB2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        right.setBackground(new java.awt.Color(204, 0, 204));
        right.setPreferredSize(new java.awt.Dimension(400, 500));
        right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\1234.png")); // NOI18N
        right.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 149, -1, 149));

        jPanel1.add(right);
        right.setBounds(0, 0, 400, 500);

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setPreferredSize(new java.awt.Dimension(400, 500));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("SIGN UP");
        left.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("USERNAME");
        left.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 85, 83, -1));

        TF3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TF3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF3ActionPerformed(evt);
            }
        });
        left.add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 111, 282, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("PASSWORD");
        left.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 157, 83, -1));

        PF3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        PF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF3ActionPerformed(evt);
            }
        });
        left.add(PF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 183, 282, 40));

        B7.setBackground(new java.awt.Color(204, 0, 204));
        B7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        B7.setForeground(new java.awt.Color(255, 255, 255));
        B7.setText("Login");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        left.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        B8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B8.setForeground(new java.awt.Color(204, 0, 204));
        B8.setText("Sign up");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        left.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 103, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("CONFIRM PASSWORD");
        left.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 153, -1));

        PF4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        PF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF4ActionPerformed(evt);
            }
        });
        left.add(PF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 282, 40));

        CB2.setBackground(new java.awt.Color(204, 0, 204));
        CB2.setText("SHOW CONFIRM PASSWORD");
        CB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB2ActionPerformed(evt);
            }
        });
        left.add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 190, -1));

        jPanel1.add(left);
        left.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF3ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        LogIn login =  new LogIn();
        login.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        String cpass = PF4.getText();
        String uname = TF3.getText();
        String pass = PF3.getText();
        if(!pass.equals(cpass)){
            JOptionPane.showMessageDialog(rootPane, "Password and confirm password not equal!", null, JOptionPane.ERROR_MESSAGE);
           
            return;
        }else{
            try{
               Connection c = Bar.getConnected();
                String sql =  "INSERT INTO registration(username, password) VALUES (?,?)";
                 PreparedStatement pst = c.prepareStatement(sql);
                    pst.setString(1,uname);
                    pst.setString(2,pass);
                    pst.executeUpdate();
                     JOptionPane.showMessageDialog(rootPane, "Proceed To Login");
                    TF3.setText("");
                    PF3.setText("");
                    PF4.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    }//GEN-LAST:event_B8ActionPerformed

    private void CB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB2ActionPerformed
        if(CB2.isSelected()){
            PF3.setEchoChar((char)0);
            PF4.setEchoChar((char)0);
        }else{
            PF3.setEchoChar('*');
            PF4.setEchoChar('*');
        }
    }//GEN-LAST:event_CB2ActionPerformed

    private void PF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PF4ActionPerformed

    private void PF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PF3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JCheckBox CB2;
    private javax.swing.JPasswordField PF3;
    private javax.swing.JPasswordField PF4;
    private javax.swing.JTextField TF3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel left;
    private javax.swing.JPanel right;
    // End of variables declaration//GEN-END:variables
}
