package bar;

/**
 *
 * @author madro
 */
public class SportsandLiq extends javax.swing.JFrame {

    /**
     * Creates new form SportsandLiq
     */
    public SportsandLiq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Tabpane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        avail_karaoke = new javax.swing.JCheckBox();
        reserve_karaoke = new javax.swing.JCheckBox();
        avail_table = new javax.swing.JCheckBox();
        bil_avail = new javax.swing.JCheckBox();
        bil_reserve = new javax.swing.JCheckBox();
        reserve_table = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        avail_ppong = new javax.swing.JCheckBox();
        avail_reserve = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("FOOD/LIQOUR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 200, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("SPORT'S/KARAOKE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 77, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 255));
        jLabel2.setText("SPORT'S BAR");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 51));
        jButton3.setText("LOG OUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\l.jpg")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 520));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 520));

        Tabpane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(255, 102, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("KARAOKE");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 120, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\16.jpg")); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 100));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("BILLIARD");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\14.jpg")); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 130, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("TABLE");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 80, 30));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\12.jpg")); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 130, 100));

        jLabel20.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 153));
        jLabel20.setText("SPORTS & KARAOKE");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 420, -1));

        avail_karaoke.setBackground(new java.awt.Color(153, 153, 153));
        avail_karaoke.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        avail_karaoke.setForeground(new java.awt.Color(255, 0, 255));
        avail_karaoke.setText("AVAIL");
        avail_karaoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avail_karaokeActionPerformed(evt);
            }
        });
        jPanel4.add(avail_karaoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 80, -1));

        reserve_karaoke.setBackground(new java.awt.Color(153, 153, 153));
        reserve_karaoke.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reserve_karaoke.setForeground(new java.awt.Color(255, 0, 255));
        reserve_karaoke.setText("RESERVE");
        reserve_karaoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserve_karaokeActionPerformed(evt);
            }
        });
        jPanel4.add(reserve_karaoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 80, -1));

        avail_table.setBackground(new java.awt.Color(153, 153, 153));
        avail_table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        avail_table.setForeground(new java.awt.Color(255, 0, 255));
        avail_table.setText("AVAIL");
        avail_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avail_tableActionPerformed(evt);
            }
        });
        jPanel4.add(avail_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 80, -1));

        bil_avail.setBackground(new java.awt.Color(153, 153, 153));
        bil_avail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bil_avail.setForeground(new java.awt.Color(255, 0, 255));
        bil_avail.setText("AVAIL");
        bil_avail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil_availActionPerformed(evt);
            }
        });
        jPanel4.add(bil_avail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 80, -1));

        bil_reserve.setBackground(new java.awt.Color(153, 153, 153));
        bil_reserve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bil_reserve.setForeground(new java.awt.Color(255, 0, 255));
        bil_reserve.setText("RESERVE");
        bil_reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil_reserveActionPerformed(evt);
            }
        });
        jPanel4.add(bil_reserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 80, -1));

        reserve_table.setBackground(new java.awt.Color(153, 153, 153));
        reserve_table.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reserve_table.setForeground(new java.awt.Color(255, 0, 255));
        reserve_table.setText("RESERVE");
        reserve_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserve_tableActionPerformed(evt);
            }
        });
        jPanel4.add(reserve_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 80, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\V.jpg")); // NOI18N
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, 130));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel30.setText("PINGPONG");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, 30));

        avail_ppong.setBackground(new java.awt.Color(153, 153, 153));
        avail_ppong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        avail_ppong.setForeground(new java.awt.Color(255, 0, 255));
        avail_ppong.setText("AVAIL");
        avail_ppong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avail_ppongActionPerformed(evt);
            }
        });
        jPanel4.add(avail_ppong, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 80, -1));

        avail_reserve.setBackground(new java.awt.Color(153, 153, 153));
        avail_reserve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        avail_reserve.setForeground(new java.awt.Color(255, 0, 255));
        avail_reserve.setText("RESERVE");
        avail_reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avail_reserveActionPerformed(evt);
            }
        });
        jPanel4.add(avail_reserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 80, -1));

        jButton4.setForeground(new java.awt.Color(255, 0, 255));
        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        Tabpane1.addTab("tab1", jPanel3);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setForeground(new java.awt.Color(102, 255, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/25.jpg"))); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 100));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("BARBEQUE");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 130, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\C.jpg")); // NOI18N
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 150, 100));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setText("TOWER");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 90, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\B.jpg")); // NOI18N
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("CHICHARON");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 150, 30));

        jLabel18.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel18.setText("MENU");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 120, -1));

        jLabel19.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 153));
        jLabel19.setText("FOOD & LIQUOR,DRINKS ");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 460, 30));

        jCheckBox1.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 0, 255));
        jCheckBox1.setText("ORDER");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 80, -1));

        jCheckBox2.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 0, 255));
        jCheckBox2.setText("ORDER");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 80, -1));

        jCheckBox3.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 0, 255));
        jCheckBox3.setText("ORDER");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 80, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\DA.jpg")); // NOI18N
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel22.setText("SISIG");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, 30));

        jCheckBox10.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(255, 0, 255));
        jCheckBox10.setText("ORDER");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\HA.jpg")); // NOI18N
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("SOFTDRINKS");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 150, 30));

        jCheckBox11.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(255, 0, 255));
        jCheckBox11.setText("ORDER");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 80, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\H.jpg")); // NOI18N
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 150, 100));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel26.setText("TEQUILA");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 110, 30));

        jCheckBox12.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(255, 0, 255));
        jCheckBox12.setText("ORDER");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 80, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\madro\\OneDrive\\Documents\\NetBeansProjects\\Bar\\src\\icon\\K.jpg")); // NOI18N
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 150, 90));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel28.setText("BEER");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 60, 30));

        jCheckBox13.setBackground(new java.awt.Color(153, 153, 153));
        jCheckBox13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(255, 0, 255));
        jCheckBox13.setText("ORDER");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 80, -1));

        jButton5.setForeground(new java.awt.Color(255, 0, 255));
        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        Tabpane1.addTab("tab2", jPanel5);

        jPanel1.add(Tabpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -30, 570, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Tabpane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Tabpane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void avail_karaokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avail_karaokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avail_karaokeActionPerformed

    private void reserve_karaokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserve_karaokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserve_karaokeActionPerformed

    private void avail_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avail_tableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avail_tableActionPerformed

    private void bil_availActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil_availActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil_availActionPerformed

    private void bil_reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil_reserveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil_reserveActionPerformed

    private void reserve_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserve_tableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserve_tableActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void avail_ppongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avail_ppongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avail_ppongActionPerformed

    private void avail_reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avail_reserveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avail_reserveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         LogIn In = new LogIn();
         In.setVisible(true); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String billiard_avail = "";
        String billiard_reserve = "";
        String pingpong_reserve = "";
        String pingpong_avail = "";
        String karaoke_avail = "";
        String karaoke_reserve = "";
        String table_avail = "";
        String table_reserve = "";
        if(bil_avail.isSelected()){
            billiard_avail = "Billiard Avail";
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SportsandLiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SportsandLiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SportsandLiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SportsandLiq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SportsandLiq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabpane1;
    private javax.swing.JCheckBox avail_karaoke;
    private javax.swing.JCheckBox avail_ppong;
    private javax.swing.JCheckBox avail_reserve;
    private javax.swing.JCheckBox avail_table;
    private javax.swing.JCheckBox bil_avail;
    private javax.swing.JCheckBox bil_reserve;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JCheckBox reserve_karaoke;
    private javax.swing.JCheckBox reserve_table;
    // End of variables declaration//GEN-END:variables
}
